os: linux
dist: xenial

branches:
  only:
  - master
  - major
  - stable
  - latest
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/
  - /^release\/\d+\.\d+\.x$/

language: node_js
node_js: 10

jobs:
  include:
    - name: linux
      os: linux
      dist: xenial
      services:
        - xvfb
      addons:
        firefox: latest
        chrome: stable

      script:
        echo "hello world from the node-10 and linux"

    - name: osx
      os: osx

      script:
        echo "hello world from the node-9 and apple"
