sudo: required
dist: xenial
services:
  - xvfb

branches:
  only:
  - master
  - major
  - stable
  - latest
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/
  - /^release\/\d+\.\d+\.x$/

language: node_js

node_js:
  - 10

addons:
  firefox: latest
  chrome: stable

before_script:
  # Setup xvfb
  - 'export DISPLAY=:99.0'
  - 'sleep 3'
  # Setup CKEditor 4 testing environment
  - pwd
  - npm install benderjs-cli -g
  - npm i
  # Setup bender test runner
  - cd ..
  - pwd
  - git clone git@github.com:ckeditor/ckeditor4-benderjs-runner.git
  - cd ckeditor4-benderjs-runner
  - npm i

script:
  - pwd
  - npm run test '../../ckeditor4-benderjs-runner-tests/bender-runner.config.json' 'path:/tests/plugins/image2'
