os: linux
dist: xenial

branches:
  only:
  - master
  - major
  - stable
  - latest
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/
  - /^release\/\d+\.\d+\.x$/

language: node_js
node_js: 10

jobs:
  include:
    - name: Chrome (Linux)
      os: linux
      dist: xenial
      services:
        - xvfb
      addons:
        chrome: stable
      before_script:
        # Setup xvfb
        - 'export DISPLAY=:99.0'
        - 'sleep 3'
        # Setup CKEditor 4 testing environment
        - pwd
        - npm install benderjs-cli -g
        - npm i
        # Setup bender test runner
        - cd ..
        - pwd
        - git clone https://github.com/ckeditor/ckeditor4-benderjs-runner.git
        - cd ckeditor4-benderjs-runner
        - git checkout t/1
        - npm i
        # Define target branches/commits
        - TARGET_BRANCH=$TRAVIS_BRANCH
        - CURRENT_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
               sh -e TARGET_BRANCH="HEAD^" && CURRENT_BRANCH="HEAD";
          fi'
      script:
        - pwd
        - echo "Running tests based on diff between $TARGET_BRANCH and $CURRENT_BRANCH"
        - npm run test "../../ckeditor4-benderjs-runner-tests/bender-runner.config.json" "$TARGET_BRANCH" "$CURRENT_BRANCH" "chrome"
