name: Run CKEditor 4 bender tests

# https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request
on: pull_request

jobs:
  update:
    runs-on: macos-latest

    steps:
      - name: Setup node
        # https://github.com/marketplace/actions/setup-node-js-environment
        uses: actions/setup-node@v1
        with:
          node-version: '10'

      - name: Fetch changes
        # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v2

      - name: Setup CKEditor 4 testing environment
        run: |
          pwd
          npm install -g benderjs-cli
          npm i

      - name: Checkout bender test runner
        # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v2
        with:
          path: ckeditor4-benderjs-runner
          repository: ckeditor/ckeditor4-benderjs-runner
          ref: master

      - name: Setup bender test runner
        run: |
          pwd
          mv ckeditor4-benderjs-runner ../ckeditor4-benderjs-runner
          cd ../ckeditor4-benderjs-runner
          pwd
          npm i

      - name: Run tests
        run: |
          pwd
          cd ../ckeditor4-benderjs-runner
          pwd
          ls -la
          npm run test '../../ckeditor4-benderjs-runner-tests/bender-runner.config.json' 'path:/tests/plugins/image2'
